### ISSUE TITLE
useNewEnum with existing connections?

### ISSUE THREAD

**Issue by duro** [typegoose/typegoose#110]
Per the latest commit to master, and the addition of the useNewEnum option, I see that the docs note that the setGlobalOptions function was added to not break usage of existing connections. I'm curious how this should be used (or if it should be used) with passing in existingConnection via `getModelForClass`? It wasn't clear from the provided docs.

**Comment by hasezoey** [comment]
> not break usage of existing connections

i think you are misunderstanding, i added the option to not break ***existing DataBases***, in the meaning of:
```ts
enum Hi {
  Hi1,
  Hi2,
}
```
would work the same, but:
```ts
enum Hi2 {
  Hi1 = "Hi 1",
  Hi2 = "Hi 2"
}
```
would completly break existing documents in an database, because it is not `["Hi1", Hi2"]` anymore, it is now `["Hi 1", "Hi 2"` (when enum has values of a string, take the string values, otherwise take the property keys)

**Comment by hasezoey** [comment]
as an update, i re-visited it again, which disabled number-enums, reasons listed at https://typegoose.github.io/typegoose/docs/decorators/prop/#enum

**Comment by hasezoey** [comment]
i will close this because it was a misunderstanding

Please comment / reopen if this was **not** the case
