### ISSUE TITLE
Error: Type of XXX property is not a string.

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#149]
## Versions

- Typegoose(NPM): 6.1.5

## What is the Problem?

I get this error:

```
Error: Type of field property is not a string.
```

for no reason.

## Code Example

```ts
import mongoose from 'mongoose';
import { prop, getModelForClass } from '@typegoose/typegoose';

const String = mongoose.Schema.Types.String;
String;

class A {
  @prop()
  _id: string;

  @prop({ lowercase: true })
  field: string;
}

getModelForClass(A);
```

**Comment by hasezoey** [comment]
could you give me a debug log about this? without it, it is hard to tell what it is (this is a probably a "legacy" error, which i didnt touch until now)

set this on the top of your entry file (at the very top, above everything else)
```ts
import { setLogLevel, LogLevel } from "@typegoose/typegoose";
setLogLevel(LogLevel.DEBUG);
```

(gist / pastebin is preferred, please no dropbox or something like it)

**Comment by lcswillems** [comment]
Can't you just copy paste this code in a TypeScript and execute it?

**Comment by hasezoey** [comment]
> Can't you just copy paste this code in a TypeScript file and execute it? It will be easier for you to debug it later

i re-read your issue again, i missed the part `const String = mongoose.Schema.Types.String;` (i first thought it was `type String = mongoose.Schema.Types.String` - this is the problem), because typescript compiles `field: string` to `design:type = String`(reflection), because you have set `String` to equal `mongoose.Schema.Types.String` it is not matching `Type.name === "String"` (`mongoose.Schema.Types.String.name` is set to `SchemaString`) - will be fixed in the next update
-> PS: re-defining default values is really bad

**Comment by hasezoey** [comment]
6.2.1 is now released
