### ISSUE TITLE
`_id` has type `any`

### ISSUE THREAD

**Issue by lcswillems** [typegoose/typegoose#189]
## Versions

- Typegoose(NPM): 6.3.0

## Issue

In the following code, `test._id` has type `any`:

```ts
import { prop, getModelForClass } from '@typegoose/typegoose';

class Test {
  @prop()
  _id: string;
}

const TestModel = getModelForClass(Test);

const test = new TestModel();
test._id;
```

**Comment by hasezoey** [comment]
(will add the original issue here when i find it)

We already had such an issue, the problem is because mongoose's `Document` Type has an `_id` of `any` and typescript uses the most generic type (which in this case is `any`), we have the `Base` class you can extend, then the `_id` gets removed from `Document` and the custom one is used (you might ask: "why is the Base class needed", this is to make sure `_id` exists and because typescript wouldnt let it work otherwise)
