### ISSUE TITLE
Strongly typed model creation

### ISSUE THREAD

**Issue by 101arrowz** [typegoose/typegoose#240]
## Describe what you need | want
When creating documents, the model constructor expects only type `any`, and so does `Model.create()`. These should be the document type instead.

```ts
import { getModelForClass, prop } from '@typegoose/typegoose'; 

class A {
  @prop();
  x: boolean;
};

const AModel = getModelForClass(A);

AModel.create({ a: 1 }); // Should be type-validated
```

## Do you have already an idea for the implementation?

Instead of using `AnyParamConstructor` internally, just use the document type. Also, use declaration merging to override the `.create()` of `mongoose.Model`.

Strong-typing the constructor parameter like something that was intentionally not done; is there a particular reason? If not, I'd be willing to create a PR to add typings for this.

**Comment by hasezoey** [comment]
https://typegoose.github.io/typegoose/guides/faq/#why-does-new-model-not-have-types

PR's are welcome
main reason why this hasnt been done is because i didnt find an suitable way without using `declare namespace mongoose` (im not so good with such types)

**Comment by 101arrowz** [comment]
I believe I've managed to get a primitive solution working by extending `mongoose.Model` with a `TypegooseModel` interface. I'll test it out and submit a PR if I can.

**Comment by 101arrowz** [comment]
The PR's been made.

**Comment by hasezoey** [comment]
thanks to `@types/mongoose@5.7.21`+ this gets closed

**Comment by FINDarkside** [comment]
This doesn't seem to work anymore, probably because mongoose now has its own types which are don't type constructor params properly. Can we re-open this?

**Comment by hasezoey** [comment]
> This doesn't seem to work anymore, probably because mongoose now has its own types which are don't type constructor params properly. Can we re-open this?

from what i know, this still works in mongoose 6.x, if properly installed

please open another issue / discussion / ask on discord with your use-case and your versions used

**Comment by FINDarkside** [comment]
Just to confirm, do you want me to make a new issue with same contents of this issue? Because the usecase is exactly the same and the example in this issue opener can be used to demonstrate how it does not work.

And I don't really see how it could work when mongoose is [typed like this](https://github.com/Automattic/mongoose/blob/master/index.d.ts#L791) and `@types/mongoose` isn't maintained anymore because mongoose now provides its own types.

**Comment by hasezoey** [comment]
from what i can tell, mongoose is "strongly typed", see https://github.com/Automattic/mongoose/blob/83a89f95e4acc8fdd29c2f2ee6ae0e6bf6add48d/index.d.ts#L796-L800 its just that it also allows other keys (sadly specific types cannot be disabled, unless overwritten)

and when it is *exactly the same use-case / feature request*, then i will have to decline, because since then i made the point that typegoose will not modify mongoose's types
