### ISSUE TITLE
Confusing / unlinked documentation about findOrCreate

### ISSUE THREAD

**Issue by dandv** [typegoose/typegoose#266]
https://typegoose.github.io/typegoose/guides/defaultClasses/#findorcreate doesn't say much about findOrCreate and doesn't link to anything.

But there's a page with more information:
https://github.com/typegoose/typegoose/blob/master/github-page/_docs/decorators/plugins.md

And one with even more:
https://github.com/typegoose/typegoose/blob/master/github-page/_guides/advanced/common-plugins.md#mongoose-findorcreate

**Comment by hasezoey** [comment]
> https://github.com/typegoose/typegoose/blob/master/github-page/_docs/decorators/plugins.md

that was where i wrote some basic-information docs about the `@plugin` decorator, will change that to something more generic

> https://typegoose.github.io/typegoose/guides/defaultClasses/#findorcreate
> https://github.com/typegoose/typegoose/blob/master/github-page/_guides/advanced/common-plugins.md#mongoose-findorcreate

these were made because when i got to typegoose this plugin was used to test typegoose's plugin decorator, and because i didnt want to remove or replace it, i just added an default-class and an common-plugins entry to show to use it with typegoose

-> as for the plugin itself, i didnt use it aside from the tests and shortly looking at the docs for it for the typegoose-documentation (but the documentation is still in an basic state)

**Comment by hasezoey** [comment]
closing because:

> https://github.com/typegoose/typegoose/blob/master/github-page/_docs/decorators/plugins.md

is just an example on how to use the `@plugin` decorator

> https://typegoose.github.io/typegoose/guides/defaultClasses/#findorcreate doesn't say much about findOrCreate

there isnt much to say aside from having the function typed

> and doesn't link to anything.

302a9a82aaa6a431b4073c9b0c81afedfa39277f
