### ISSUE TITLE
Implicitly setting "Mixed" is not allowed! warning when assign property as Mixed type

### ISSUE THREAD

**Issue by ricosandyca** [typegoose/typegoose#291]
## Versions

- NodeJS: 12.16.3
- Typegoose(NPM): 7.2.0
- mongoose: 5.9.18
- mongodb: 4.0.18

## What is the Problem?

Got `Implicitly setting "Mixed" is not allowed! (User, details)` warning when assign property as Mixed type

## Code Example

```ts
import { Schema } from 'mongoose'
import {
  getModelForClass,
  modelOptions,
  prop,
  Ref
} from '@typegoose/typegoose'

import { File } from './File'

enum Role {
  ADMIN = 'admin',
  USER = 'user',
  PARTNER = 'partner'
}

export type UserDetails = {
  email?: string
}

@modelOptions({ schemaOptions: {
  timestamps: true,
  collection: 'users'
}})
export class User {
  @prop({ required: true }) username!: string
  @prop({ ref: 'files' }) profilePic?: Ref<File>
  @prop({ enum: Role, default: Role.USER }) role?: Role
  @prop({ type: Schema.Types.Mixed }) details?: UserDetails
}

export default getModelForClass(User)
```

## Do you know *why* it happenes?

*no*

Is Mixed type disabled on this typegoose version or just a bug?

**Comment by hasezoey** [comment]
sorry that there is confusion about this, currently (by default) an warning is given if an property will be `Mixed`

you can disable this warning, or let it error instead of warn with [model option `allowMixed`](https://typegoose.github.io/typegoose/docs/decorators/modelOptions/#allowmixed)

3ed06e5097ab929f69755676fee419318aaec73a should better represent what it actually means

**Comment by ricosandyca** [comment]
@hasezoey thanks, it works.
