### ISSUE TITLE
Can't extend both Base and TimeStamps

### ISSUE THREAD

**Issue by arnaudpeich** [typegoose/typegoose#295]
Hi,

The documentation on [default classes](https://typegoose.github.io/typegoose/guides/defaultClasses/) gives the following example:

```ts
import { TimeStamps, Base } from '@typegoose/typegoose/lib/defaultClasses';

class SomeClass extends TimeStamps, Base {} // this class now has the types of "TimeStamps" & "Base"
```

which leads to TS error 1174:

> Classes can only extend a single class

Instead of the code given in the documentation, one could use this approach, for instance: https://stackoverflow.com/a/26961710/1345985

It would be even nicer if a combination of the two classes was made available (I even wonder if `TimeStamps` could simply extend `Base` since timestamps generally apply to top-level documents).

**Comment by hasezoey** [comment]
thanks for noticing this, i thought i already removed this example
it was planned for ~7.0 that default classes extend Base, but forgotten to actually do it

**Comment by hasezoey** [comment]
removed since 98879d2251c34b9059599a5e63e112369d3c07e9

**Comment by alimoli** [comment]
Any news about this?

> It would be even nicer if a combination of the two classes was made available (I even wonder if TimeStamps could simply extend Base since timestamps generally apply to top-level documents).

**Comment by hasezoey** [comment]
> Any news about this?

yes since typegoose 8, `Base` is a interface to implement, not a class anymore

**Comment by alimoli** [comment]
Oh yes, just double checked.
But I have a doubt about this.
Implementing the Base interface I have to declare the property fields in this way in order to avoid errors.

<img width="432" alt="Screenshot 2022-0
1-28 at 14 37 32" src="https://user-images.githubusercontent.com/68189985/151556217-29017c82-7549-407a-a5d0-4bfbb3936b34.png">

<img width="425" alt="Screenshot 2022-01-28 at 14 38 56" src="https://user-images.githubusercontent.com/68189985/151556457-edec26cc-6620-48a6-820a-310108de8c4b.png">

But assuming this model creation:

```
export class Charge extends TimeStamps implements Base {
   <some props here>
}

export const ChargeModel: ReturnModelType<typeof Charge> = mongoose.models.Charge || getModelForClass(Charge)

// Create the model
ChargeModel.create({
        <some props here>
})
```

When I create the model in this way, the properties passed to create the method are always `any` so I can pass whatever.
So trying to force that behavior I tried to cast the properties as `Charge`.
But in this case, I have to pass also the `_id` and `id`.

Any tip about this?

**Comment by hasezoey** [comment]
> Any tip about this?

you can use both a interface and a class with the same name and they merge, yes it is a bit more "untidy", but currently the only way to do it (from what i know):

```ts
interface User extends defaultClasses.Base {
  _dummyprop: never;
}

class User extends defaultClasses.TimeStamps {
  @prop()
  public username?: string;
}

// User now has all types, from itself, from TimeStamps and from Base
// on runtime, it still only extends TimeStamps
```

Note: if you have some specific formatting on or lints, you will have to define a "dummyprop" to make the lints / errors go away (otherwise for formatting it might change to `type User = defaultClasses.Base`, which is not compatible)

**Comment by alimoli** [comment]
Thank you for the explanation @hasezoey !
It seems like the "merge" doesn't work (lints/errors remain) if you need to export the class. 😌

**Comment by alimoli** [comment]
I think I found a way.
1. Create a base class extending `TimeStamps`
2. Use the base class to create the real model and implement the Base class for `_id` and `id` support

```ts
export class ModelBase extends TimeStamps {
    @prop()
    etc.
}

@modelOptions(...)
export class Model extends ModelBase implements Base {
     _id!: mongoose.Types.ObjectId;
     id!: string;
}

getModelForClass(Model)
```

I will check out this solution and I will come back to you with feedback. 😀

**Comment by theDanielJLewis** [comment]
@alimoli, did that work?

[This](https://github.com/typegoose/typegoose/issues/295#issuecomment-1024257151) doesn't seem to work for me, or maybe I'm doing something wrong. Whenever I try to call the object with ._id, I get errors from Typescript.

**Comment by smolinari** [comment]
@theDanielJLewis - What I did was just create my own base entity with the two date/time properties for timestamps and implement `Base` for the missing types. For code reuse, I simply extend from my new base entity. 

It looks like this:

```ts
@ModelOptions({
  schemaOptions: {
    timestamps: { updatedAt: 'modifiedAt' },
    toObject: { virtuals: true }
  }
})
@Plugin(autopopulate as any)
export class BaseEntity implements Base {
  _id!: Types.ObjectId

  id!: string

  @Prop({ ref: () => UserEntity, autopopulate: { maxDepth: 1 } })
  public createdBy?: Ref<UserEntity>

  @Prop({ ref: () => UserEntity, autopopulate: { maxDepth: 1 } })
  public modifiedBy?: Ref<UserEntity>

  @Prop()
  public modifiedAt!: Date

  @Prop()
  public createdAt!: Date
}
```

Scott
