### ISSUE TITLE
Requesting for `.parent()` and `.ownerDocument()` in a document class

### ISSUE THREAD

**Issue by karrui** [typegoose/typegoose#306]
## Which feature

- [Accessing parent of a subdocument](https://mongoosejs.com/docs/subdocs.html#subdoc-parents)

Mainly requesting for the `.ownerDocument()` and `.parent()` features.

## Code Examples

Most of the time used in pre-validations:

```js
SomeSchema.pre('validate', function (next) {
  const isParentSomething = this.parent().something
  if (!isParentSomething) {
    return next(new Error('Subdoc cannot be inserted into parent without something'))
  }
}
```

Currently, in the Typegoose equivalent,

```js
@pre<SomeClass>('validate', function (next) {
  // Property 'parent' does not exist on type 'DocumentType<SomeClass>'.
  const isParentSomething = this.parent().something
  ...
})
```

Basically requesting for `this` in pre/post/ other mongoose hooks to also include the `parent` and `ownerDocument` property. 

## Additional Notes

I'm quite new to Typegoose, so if there is another way to do what I asked without using `.parent` or `.ownerDocument`, I'd be very happy too!

**Comment by hasezoey** [comment]
these need to be typed in `@types/mongoose`, and from what i know, they currently dont exist there (so your "mongoose example" should also have no types)

**Comment by karrui** [comment]
It exists in the `Embedded` class that extends a `MongooseDocument`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mongoose/v4/index.d.ts#L1438

**Comment by hasezoey** [comment]
if you think this is the right type, then overwrite `this`:

```ts
function some(this: ADifferentType, param1: any) {}
```

**Comment by trappar** [comment]
This is also currently an issue with subdocuments. I haven’t been able to find any good way to type them. The problem is that even if you use `Embedded`, it won’t really help since it’s not a generic. This means that when you use `parent()`, or any of the other methods described in `Embedded` it won’t return a document that’s aware of what type the parent document is.

My temporary solution is to just create a custom type which is a combination of DocumentType and custom types for the methods I want to use. Pretty poor solution... but at least it works.

**Comment by hasezoey** [comment]
@trappar i would have recommended to AND the DocumentType and Embedded

**Comment by trappar** [comment]
I believe that’s what I did. It doesn’t help with the issue I mentioned. `parent` returns just a Document rather than a DocumentType of my parent Document.

**Comment by hasezoey** [comment]
closing because stale & not a typegoose issue
