### ISSUE TITLE
Can we add custom error messages to be displayed when data is not consistent with @prop options?

### ISSUE THREAD

**Issue by AlexDeKatz** [typegoose/typegoose#319]
In Mongoose we can add custom error messages to override the default message that is thrown when inserting/updating data violates the Schema.
Eg:

```ts
var breakfastSchema = new Schema({
  eggs: {
    type: Number,
    min: [6, 'Too few eggs'], //Custom error message
    max: 12
  },
  bacon: {
    type: Number,
    required: [true, 'Why no bacon?'] //Custom error message
  }
})
```
Currently we get the default error messages when data does not match the schema specified,

### Versions

- typegoose: 7.2.0
- mongoose: 5.9.20

**Comment by hasezoey** [comment]
yes this is supported, because the options used are passed down to mongoose, and are not being processed by typegoose, the only thing is that typegoose maybe not have the correct types for this *yet*, so if there should be any option that supports this, and typegoose dosnt have the types for this - please say it, it will be added (until an version is released add `// @ts-expect-error` above the line with the option)

**Comment by AlexDeKatz** [comment]
Thank you for the insight.
