### ISSUE TITLE
Is it possible to create a generic object as prop?

### ISSUE THREAD

**Issue by TheZadok42** [typegoose/typegoose#354]
I am trying to have one prop as a generic object
```typescript
[name: string]: string []
```

But if I set it as type, it changes to `Mixed`.  
Is there a way to solve it?

**Comment by hasezoey** [comment]
could you please give more information on what you are trying to do (like an full class)?

**Comment by TheZadok42** [comment]
For example, for different customers I want to send different types of mails

So like:
```
{
     "type1": ["real", "person"],
     "type2": ["another", "person"]
}
```

**Comment by hasezoey** [comment]
for this i would either recommend nestedDiscriminators or `type: mongoose.Schema.Types.Mixed` and `public prop: { [key: string]: string[]`

**Comment by TheZadok42** [comment]
Will this also add validation or is it will converted to mixed?

**Comment by hasezoey** [comment]
i didn't suggest maps, because typegoose currently doesn't handle `type: [String]` (planned for 8.0 / some minor version)

so currently the only ways to do this:
- if `key` is finite and known, try nestedDiscriminators (validated)
- another option would be to merge an custom schema into the class (by running `buildSchema` then some `schema.clone` and `addModelToTypegoose`) (validated, and correct types, but more code)
- or using Mixed (unvalidated by default mongoose validators)
