### ISSUE TITLE
Connection specific Model Names / Models

### ISSUE THREAD

**Issue by goulash1971** [typegoose/typegoose#401]
## Describe what you need | want

A change to the `getModelForClass` function that would permit the same class to be used for models that exist in different MongoDB databases (as determined by the `Mongoose` specified as an `existingConnection`).

Currently this is not permitted because only a single model name can be generated for a class (irrespective of the `Mongoose`) and this is then cached by name in the `models` data cache.

## Do you have already an idea for the implementation?

From a look at the source code the `name` of the model comes from `getName` which looks at the class decorator and uses the `IModelOptions` from the decorator i.e. does not use the `IModelOptions` passed into the `getModelForName`.

Without checking for ripple effects / regressions, there are various solutions ...

(1) change the `models` cache so that it is dual keyed according to the connection and the model name, 

(2a) do not change `getName` but allow the mode name generated from `getName` to be overridden using the `IModelOptions` passed into `getModelForClass`, or

(2b) pass the `IModelOptions` specified for `getModelForClass` into `getName` such that they can be merged and used to generate the correct name

Therefore the calling code could specify the `customName` property as part of the `getModelForClass` call.

There is also an alternative option which is to allow the `customName` to be specified as a "generator function" or a string, and if it's a generator function pass the `cls` and the `IModelOptions` into the generator.  However, given that this generator would be specified on the decorator, you would still need to pass the `IModelOptions` given to the `getModelForClass` so that the `existingConnection` could be extracted and used to prefix the model name.

**Comment by hasezoey** [comment]
from my knowledge, connections in mongoose dont have an name, only an id (`0`, `1`)
-> this is currently not easy to implement, because (on your proposal) you would set the connection on `getModelForClass`, which would mean to change the name there, which can only be changed inside an `@modelOptions`

PS: `getModelForClass` doesnt decide on the name, its `getName`

**Comment by goulash1971** [comment]
Hi @hasezoey 

Yes, I guess I was asking for something different.

I'll put something together and send it through as a pull request.

Thanks

**Comment by hasezoey** [comment]
will look into this for 8.0

**Comment by MohitVachhani** [comment]
hey @goulash1971 

Are you asking to cache model using two attributes.
1. model name.
2. model connection.

**Comment by hasezoey** [comment]
thanks to #502 (typegoose `7.6.0`), it is possible to change the name from `getModelForClass` (/ `buildSchema`), so the most reasonable solution would be to allow `customName` to be an generator function
(and with this, my first comment in this issue is outdated)

anything new / else to consider @goulash1971 ?

**Comment by hasezoey** [comment]
i will close this for now because of no new developments, and the names can be overwritten from `getModelForClass` / `buildSchema` / `getDiscriminatorModelForClass` directly (alongside other options) and `customName` can also be a function

if anyone has something to add, i might re-open this issue
