### ISSUE TITLE
virtual set with Model.create() problem

### ISSUE THREAD

**Issue by blatoo** [typegoose/typegoose#412]
## Versions

- typegoose: 7.4.2
- mongoose: 5.10.15

Hi all, 

I got a problem with the set funtion of a virtual property. It won't let me create a doc without the virtual property. 

For example, the example in the documentation with `User` Model: 

```ts
class UserClass {
  @prop({ required: true })
  public firstName?: string

  @prop({ required: true })
  public lastName!: string

  public get fullName() {
    return `${this.firstName} ${this.lastName}`
  }

  // here is the problem part!
  public set fullName(fullName: string) {
    const [firstName, lastName] = fullName.split(" ")
    this.firstName = firstName
    this.lastName = lastName
  }
}

export const User = getModelForClass(UserClass)
```

I want to simply create a user, but typescript shows me an error:

```ts
User.create({firstName: "Marcus", lastName: "Klein"}) // Error: Property fullName is missing... 
```

However, if I input the fullName, then, it will be ok, but it is not what I want...
```ts
User.create({firstName: "Marcus", lastName: "Klein", fullName: "Marcus Klein"}) // it is ok...
```

What is the problem in my code?

**Comment by hasezoey** [comment]
known issue, this is because typescript dosnt differentiate between `set` and an normal property, so it cannot be excluded in an middleware type, you have to exclude these properties yourself

like:
`.create({} as YourClassHere)` (this might only work in some cases)
you could also define the get&set as optional with `?`, but this will make typescript complain everywhere where you use it that it might be undefined

**Comment by blatoo** [comment]
@hasezoey Thanks for the answer. I tried the `.create<any>({...})` and `.create({...} as any)` both can solve this typescript complain. Also the virtual set function works! 👯
