### ISSUE TITLE
[Request] document the fact that class names must be globally unique

### ISSUE THREAD

**Issue by captaincaius** [typegoose/typegoose#46]
## Describe what you need | want

Hi.  I read through the code a bit, and correct me if I'm wrong, but it seems typegoose maintains a registry that maintains mongoosey information, and that registry is keyed by the name of the class as it's defined.

I think this creates a gotcha that most users won't realize that if they use the same class name in different files, things will very likely break.

So:

1. I think this gotcha should be documented.
2. This may sound naive since I've just barely looked at the code today, but can't we keep the registry ON the classes themselves instead of having a singleton, which would avoid this gotcha entirely?

## Do you have already an idea for the implementation?

Yes - Assuming it's option one, I think I could submit a PR to README that explains this pretty fast.

And if it's option 2, I wouldn't mind taking a whack at it either ;).

**Comment by hasezoey** [comment]
At which code version did you look at?

- `master` - v5.x
or
- `r6/master` - v6.x

other references:
- introduction of customName (& doc note) f73cca004682e85a63896353c9dcfc1311c2b464
- disabling it because it was interfering with some things ac4964a2e904cfd6eba625d925a5bda65c9f4a26
- re-enabling it thanks to DEO ada5cfb81798137aebb02dc68159d93809f3f828

otherwise the docs already guide you through it https://typegoose.github.io/typegoose/guides/advanced/models-with-same-name/

---

im closing this now, because it seems you are asking for a feature that is already implemented

**Comment by captaincaius** [comment]
Yup you're right - I was looking at master, assuming it was the latest.  My bad.  r6 is quite different, so I'll look at that branch going forward.

And thanks for the links!  Yes, it looks like there's a test specifically for this case :+1:

This project is making amazing progress!
