### ISSUE TITLE
How to define array of refs?

### ISSUE THREAD

**Issue by finom** [typegoose/typegoose#486]
I'm trying to figure out how to use Typegoose. By the first look it looks good but digging deeper makes me have more questions than answers. The most important thing is how to define array of refs? Documentation doesn't give me an answer on that question (except of the arrayProp decorator which is deprecated), instead it says how to define array or objects or array of primitives. Googling that I've found that I could do it like that https://github.com/yurivangeffen/array-typegoose/blob/master/src/Project.ts 
```js
export class Project {
  @prop({ ref: () => User, required: true })
  public users!: Ref<User>[];
}
```
But it doesn't make sense since prop is defined as a "singular" ref, but type is define as an array. Making `doc.users.push(objectId)` is OK for TypeScript but executing this code obviously throws an error "push is not a function". Thank you.

**Comment by hasezoey** [comment]
sorry that it is not really mentioned in the docs

> But it doesn't make sense since prop is defined as a "singular" ref, but type is define as an array.

it makes sense, because the reflection (`: Ref<User>[]`) is of type `Array`, and it is how all array types in typegoose work, by using the reflection

---

here an example from the typegoose tests:

https://github.com/typegoose/typegoose/blob/a1fac7525f19a215a342437afe0a336656d43e41/test/models/user.ts#L62-L63

**Comment by finom** [comment]
@hasezoey hmm, how typegoose supposed to "understand" this is an array? `Ref<Interface>[]` is just a type, and as far as I know you can't get "type value" and use it in your code to do something except of other type definitions.

```js
 @prop({ ref: Car }) 
 public previousCars?: Ref<Car>[]; 
```
`ref: Car` means that `previousCars` is going to contain ObjectID as a value, not an array of it. `Ref<Car>[]` says that the property is an array with corresponding methods (push etc), and there is a mismatch: `@prop` decorator says this is a "single value field", but type says this is an array. I've just tried to use the deprecated `@arrayProp` decorator and it worked as expected by creating `[]` as property value.

**Comment by hasezoey** [comment]
thanks to tsconfig option `emitDecoratorMetadata` reflections are emitted (metadata), which can then be used at runtime, [but they are not perfect yet](https://github.com/microsoft/TypeScript/issues/7169)

that is also the reason `arrayProp` got deprecated, because an array can be detected (and forced with the second parameter to `@prop`)

**Comment by finom** [comment]
@hasezoey I also tried to use the second parameter, but what it should be? `[mongoose.Types.ObjectId]` doesn't work for example. Also IMO a requirement to update tsconfig to use this library is an anti-pattern side-effect. I wouldn't like to adapt my environment to use one or another library.

**Comment by finom** [comment]
I found out by reading the library code that the second argument is just a number. Docs really need to be updated...
```js
import { WhatIsIt } from '@typegoose/typegoose/lib/internal/constants';

@prop({ ref: () => Company, required: true }, WhatIsIt.ARRAY)
  public clientOfCompanies: Ref<Company>[];
```

**Comment by hasezoey** [comment]
totally forgot about this page, we have documentation about reference array: https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes

> Also IMO a requirement to update tsconfig to use this library is an anti-pattern side-effect. I wouldn't like to adapt my environment to use one or another library.

sorry but this cannot be changed, the option `experimentalDecorators` is needed to even use decorators, and `emitDecoratorMetadata` is needed to have easy type usage instead of defining everything manually over and over (anti duplication)

> I also tried to use the second parameter, but what it should be?

this is actually documented: https://typegoose.github.io/typegoose/docs/api/decorators/prop

from the docs:
> `kind` is to overwrite what kind of prop this is (None = Normal, Array = for arrays, Map = for Maps) (should be auto-inferred)

**Comment by finom** [comment]
> this is actually documented

It doesn't says that this is a number or an enum property. I've tried to use `Array` constructor and `"Array"` string as an argument, obviously it didn't work.

**Comment by hasezoey** [comment]
i hope the (automatically) mentioned commits fix your problem with the documentation

**Comment by finom** [comment]
@hasezoey looks good, thank you!
