### ISSUE TITLE
How to get document ID in @instanceMethod

### ISSUE THREAD

**Issue by kdong007** [typegoose/typegoose#63]
e.g:

```ts
class TestDoc{
  @instanceMethod
  getSomething(){
        this.id; // property does not exist
        this._id; // property does not exist
  }
}
```

**Comment by hasezoey** [comment]
when you are using v 6.0.0, the method decorators `instanceMethod` & `staticMethod` are deprecated (completly useless)

otherwise when using 6.0.0, there are default classes, when you want _id, then you could use the class `Base`

https://typegoose.github.io/typegoose/guides/defaultClasses/

otherwise, please always provide your typegoose version

**Comment by kdong007** [comment]
@hasezoey 
two issues:
1. `Base` has `_id` but no `id`
2. overridng `_id` type gives error `Property '_id' in type 'XXX' is not assignable to the same property in base type 'Base'.`

**Comment by hasezoey** [comment]
> Base has _id but no id

i know, i didnt include it because `id` is inconsistent in mongoose, for some reason

> overridng _id type like @prop() _id:String gives error Property '_id' in type 'XXX' is not assignable to the same property in base type 'Base'.

for fields that are default on mongoose (like `_id`, `id` or when enabled `createdAt` & `updatedAt`) cannot be overridden, so like in the Base class, use it without any `@prop` decorator (take the default class file as reference)

**Comment by B-Stefan** [comment]
@kdong007  Do you think this is a typing problem 
or are the `.id` / `._id` properties not present during the runtime? 

You could verify this by using something like : 

```
class TestDoc{
  @instanceMethod
  getSomething(){
       console.log(JSON.stringify(this, null, 4))
      //   this.id; // property does not exist
      //   this._id; // property does not exist
  }
}
```

**Comment by hasezoey** [comment]
@B-Stefan because he wrote `Base has _id but no id` where `Base` is a defaultClass, which only has `_id` and not `id` he probably meant it is a type issue
