### ISSUE TITLE
Mocking getModelForClass

### ISSUE THREAD

**Issue by gepd** [typegoose/typegoose#69]
Hi, I'm using typegoose with type-graphql and I want to write some test without hit the database

in type-graphql I've

```typescript
@Query(() => [User])
  async users(): Promise<User[]> {
    return userModel.find();
  }
```

So I want to mock `userModel.find` but I haven't find the way. 

Using [`ts-mock-imports`](https://github.com/EmandM/ts-mock-imports) I'm doing

```typescript
import * as Us from "../../entity/User";

describe("User Resolvers", () => {
  let itemMock: MockManager<Us.User>;
  let clientResolver: ClientResolver;

  beforeEach(() => {
    itemMock = ImportMock.mockClass(Us, "User");
    userResolver = new UserResolver();
   });

  it("User Test", async () => {
    itemMock.mock("getModelForClass", {
      find: async () => Promise.resolve({id: 1, name: "name"})
    });

    const result = await userResolver.users();
    console.log(result);
  });
});
```

But the test never ends, does anyone knows what I'm doing wrong or a better way to do this?

**Comment by hasezoey** [comment]
typegoose dosnt allow mocking, in the sense of that typegoose dosnt modify anything related to actually querying, this is still mongoose things, so mongoose must support this - otherwise typegoose is *entirely* offline

-> i will close this because it is not a typegoose issue / not "officially" supported

**Comment by gepd** [comment]
ok thanks for your help
