### ISSUE TITLE
How can I populate nested documents in Typegoose?

### ISSUE THREAD

**Issue by mad-coder-365** [typegoose/typegoose#773]
Let's say I have 3 schemas.

```ts
class User {
    @Prop()
    name: string
}

class Exam {
    @Prop()
    name: string

    @Prop({ ref: () => Exam }, PropType.ARRAY)
    examReq?: Ref<Exam>[]
}

class UserExam {
    @Prop({ ref: () => User })
    userId: Ref<User>

    @Prop({ ref: () => Exam })
    examId: Ref<Exam>
}
```
How can I populate all these nested documents while doing a find? **I tried the following and the exam is getting populated but examReq is returning empty.**

`userExamModel.find({_id: id}).populate('examId').populate('examId.examReq')`

Using mongoose.set('debug', true) I get the following

```
Mongoose: userexams.find({ userId: new ObjectId("63838b58b0a823d0080a9617") }, { projection: {} })
Mongoose: exams.find({ _id: { '$in': [ new ObjectId("6386370d9e84185be06422f7") ], [Symbol(mongoose#trustedSymbol)]: true }}, { skip: undefined, limit: undefined, perDocumentLimit: undefined, projection: {}})
```

## Versions
- NodeJS: 18.12.0
- Typescript: 4.9.3
- Typegoose: 9.13.1
- mongoose: 6.7.3
- mongodb: 6.0.1

**Comment by teynar** [comment]
If you add populate several times only the last one will take effect, you can check its documentation here [Mongoose API Docs - Document.prototype.populate](https://mongoosejs.com/docs/api/document.html#document_Document-populate) and here [Populating Multiple Paths - Mongoose](https://mongoosejs.com/docs/populate.html#populating-multiple-paths).

For your use case you can just provide an array with the paths you want to populate.

Also, just a quick tip about field naming, it would be better if you name the reference fields without the id suffix because if you don't after you populate the object you will have to navigate it like user.examId which is a bit odd.

You can use findById as well instead of querying for the _id!

**Comment by hasezoey** [comment]
For reference, this was [already asked on StackOverflow](https://stackoverflow.com/questions/74618080)

**Comment by hasezoey** [comment]
Extending on what @teynar already said (and what i posted in the SO question):

A workaround for this case would be:

```typescript
.populate({ path: 'examId', populate: { path: 'examReq' } });
// Note that just "examId.examReq" does not work
```

Which results in 2(3 if you count `find` itself) different queries anyway, so it would be the same as doing:

```typescript
const doc = await Model.findOne({});
await doc.populate('examId');
await doc.populate('examReq');
```
