### ISSUE TITLE
Is typegoose fully compatible TypeScript 5 that has implemented new decorators protocol and claimed it is not compatible with emitDecoratorMetadata

### ISSUE THREAD

**Issue by grimmer0125** [typegoose/typegoose#807]
From this article, https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators, there is a sentence This _new decorators proposal is not compatible with --emitDecoratorMetadata, and it does not allow decorating parameters.Future ECMAScript proposals may be able to help bridge that gap._

I'd like to try typegoose and it would be great if someone could help with this question.

**Comment by smolinari** [comment]
From my understanding, because of the missing feature of emitting metadata in the new EcmaScript decorators, TypeScript has left the `--emitDecoratorMetadata` flag in version 5, so everything should still work as it used to. So, Typegoose should still work fine with TS v5 too. 

Scott

**Comment by hasezoey** [comment]
from my understanding the decorators basically work the same and should be compatible (but not both at the same time).

also from my understanding the metadata output from typescript was not (yet) updated to use ES decorators and will still use the old "legacy proposal decorators" (`experimentalDecorators`) and also both implementations (legacy and ES decorators) use (at least slightly) different objects and so are not inter-compatible and you would have to use either but not both (and because `emitDecoratorMetadata` still uses the legacy decorators, you will have to also use the legacy decorators).

also note that [typegoose can work without `emitDecoratorMetadata`](https://typegoose.github.io/typegoose/docs/guides/use-without-emitDecoratorMetadata)

PS: i have not tested the new decorators or typescript version yet, so my understanding is coming from having read the changelog

**Comment by grimmer0125** [comment]
@hasezoey , @smolinari 
Thank you for the explanation. Is my below understanding correct? 
1. typegoose does not use the new decorator proposal yet, so it requires `experimentalDecorators` and `emitDecoratorMetadata`.
2. Since `experimentalDecorators` is required, the whole codebase of a project that uses typegoose can not use the new decorator proposal, even if the code is not related to mongo/typegoose.

**Comment by smolinari** [comment]
@grimmer0125 - You can use Typegoose without `emitDecoratorMetadata`. For the rest, you are correct. I'm not sure if you see that as a negative though. If you do, you shouldn't. Although TS still calls their decorator implementation experimental, they are very stable. NestJS is a very good framework that has been using them for years. The hope of the TS team is for the EcmaScript decorators to reach feature parity to TS' experimental decorators. There are a couple of proposals in the ES pipeline to make that happen. 

Scott

**Comment by hasezoey** [comment]
> typegoose does not use the new decorator proposal yet, so it requires experimentalDecorators and emitDecoratorMetadata.

basically yes

> Since experimentalDecorators is required, the whole codebase of a project that uses typegoose can not use the new decorator proposal, even if the code is not related to mongo/typegoose.

they could, as long as no typegoose or metadata is required

---

as a note, from my understanding legacy decorators and ES decorators should work interchangeably (at least from typegooses POV), as long as `emitDecoratorMetadata` is not used
