### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by wasya243** [typegoose/typegoose#822]
I get the following issue and do not know how to fix it ->  Class extends value undefined is not a constructor or null. Here is the zip file to test against. Please help! It's not exactly typegoose issue, but probably related, so that is why I created this ticket.
[typegoose-circular.zip](https://github.com/typegoose/typegoose/files/11232597/typegoose-circular.zip)

**Comment by hasezoey** [comment]
please dont use zip-file uploads, if they are single-files either directly include them in your issue, or paste them on gist.github.com or (preferably) put up a reproduction repository that can be run directly

---

commonly the `Class extends value undefined` seems to be a JS error, because you are trying to circularly extend something (where one chain is starting with `undefined`, which is invalid to extend from)

you can try to debug your circular issues with either [dpdm](https://www.npmjs.com/package/dpdm) or [madge](https://www.npmjs.com/package/madge) (note that i have not used either of them yet)

**Comment by wasya243** [comment]
@hasezoey thanks, resolved using think link https://medium.com/visual-development/how-to-fix-nasty-circular-dependency-issues-once-and-for-all-in-javascript-typescript-a04c987cf0de
