### ISSUE TITLE
Why is the `__v` property missing in the type of the object returned by `Document#toObject`?

### ISSUE THREAD

**Issue by aderchox** [typegoose/typegoose#848]
The object returned by `Document#toObject` method has the `__v` key in it, but it's missing in the type:
```ts
    const insertedNote = await NoteModel.create(note);
    const _noteToReturn = insertedNote.toObject();
    _noteToReturn.__v // ⬅ missing
```
Error:
> Property '__v' does not exist on type 'Note & { _id: ObjectId; } & Required<{ _id: ObjectId; }>'.ts(2339)

## Versions

It's `"@typegoose/typegoose": "^11.0.3"`

**Comment by hasezoey** [comment]
probably because `toObject` and `toJSON` return the `RawDocumentType`, meaning unless you have those properties defined on your class they are not automatically included

**Comment by aderchox** [comment]
Thanks, although I'm not versed enough in Typescript to tell this, don't you think that's something expected from Typegoose? Why add it manually on my classes if it has nothing to do with my data? In my opinion that could be confusing when I forget that __v isn't about my own data or when someone else reads the code.

**Comment by aderchox** [comment]
Oh and I've realized that it doesn't contain things like `updatedAt` and `createdAt` too, added through decorators (I've added these two using `@modelOptions({ schemaOptions: { timestamps: true } })`) and I have no way to add duplicates, so I have to remove the decorator definition and re-add them defining them myself, which isn't interesting.

**Comment by smolinari** [comment]
> Why add it manually on my classes if it has nothing to do with my data? 

Your class determines what types are in your class or rather, which types you expect to work with in the class. If you don't expect to use `__v` don't add it to your class. 

It will still be there though, because `__v` is part of Mongoose, so sort of internal to Mongoose. You can also stop its generation, if you want. However, it also has a good reason to be there. 

https://mongoosejs.com/docs/guide.html#versionKey
https://mongoosejs.com/docs/guide.html#optimisticConcurrency
http://aaronheckmann.blogspot.com/2012/06/mongoose-v3-part-1-versioning.html

So, if you want to use versioning (aka MVCC) in order to have optimistic updates of data (Mongoose default is only array data) i.e. not having one user overwrite the changes of another user incorrectly, you'll need to keep the version key. 

Scott

**Comment by smolinari** [comment]
> Oh and I've realized that it doesn't contain things like updatedAt and createdAt too

Same thing. If you expect to add `updatedAt` and `createdAt` types/ fields, add them to your class. There is a helper class for that in Typegoose: https://typegoose.github.io/typegoose/docs/guides/default-classes/#timestamps

So you can extend from this class to get both the fields, types and the turned on timestamps option. 

I just have a "base" class, I extend any major entities from:

```ts
@Plugin(autopopulate as any)
export class BaseEntity implements Base {
  _id!: Types.ObjectId

  id!: string

  @Prop({ ref: () => UserEntity, autopopulate: { maxDepth: 1 } })
  public createdBy?: Ref<UserEntity>

  @Prop({ ref: () => UserEntity, autopopulate: { maxDepth: 1 } })
  public modifiedBy?: Ref<UserEntity>

  @Prop()
  public modifiedAt!: Date

  @Prop()
  public createdAt!: Date
}
```

In the end, it is better to define your all your types/ fields in your entity classes explicitly, because that is where future you and any other developer will be going to look for the answer to the question "what is this entity all about?". If things are miraculously there in your data and you don't expect to have those devs use the fields, then they shouldn't be typed in your class. And yet, you should still document their existence to explain why the field is there, like `__v`. 

Scott

**Comment by aderchox** [comment]
Thanks @smolinari, I didn't think of extending a Base class. Your Base class is neat!
(The Discord link is link to a private server? It doesn't let me in. `"This link is to a server you don't have access to"`)
Also thanks for the explanation on version key.
