### ISSUE TITLE
Typegoose are types incorrect for when rawResult: true is set within findOneAndUpdate middleware

### ISSUE THREAD

**Issue by FullStackSteve** [typegoose/typegoose#886]
## Versions

- System: macos 
- NodeJS: v16.19.1
- Typescript: ^5.1.6
- Compiler / Transpiler: tsc
- Typegoose(NPM): ~11.4.1
- mongoose: ~7.4.4
- mongodb: 4.9.1

## What is the Problem?

Incorrect types for the `doc` in the `post` `findOneAndUpdate` middleware when `rawResult: true` is set as option to the `model.findOneAndUpdate(...)` method

## Code Example

`// @ts-ignore` is required below in order to use the `doc.value.save()` prop as `doc.save()` does not work when `rawResult: true` is passed:

```ts
// MongoDB: 5.0 (Docker)
// Typescript 4.9.5
import { getModelForClass, prop, post } from '@typegoose/typegoose'; // @typegoose/typegoose@11.5.1
import * as mongoose from 'mongoose'; // mongoose@7.5.4

@post<User>('findOneAndUpdate', function (doc, next) {
  // @ts-ignore
  doc.value.id = doc.value._id;  
  // @ts-ignore
  doc.value.save();
  next();
})
class User {
  @prop()
  public id: string;

  @prop()
  public username?: string;
}

const UserModel = getModelForClass(User);

async function main() {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  const doc = new UserModel({ username: 'user1' });

  const upsertResult = await UserModel
    .findOneAndUpdate({}, { username: 'user1' }, {
      upsert: true,
      new: true,
      rawResult: true
    })
    .exec();

  console.log(doc);

  await mongoose.disconnect();
}

main();
```

## Do you know *why* it happens?

*no* - but assume that the types need to change in the middleware to reflect the `rawResult: true` option

---

**Comment by FullStackSteve** [comment]
The middleware type for the `doc` parameter should probably be `ModifyResult<T>`

**Comment by hasezoey** [comment]
there is currently no way to distinguish between `rawResult: true` and false inside a hooks types, because that is set on the operation level, and hooks dont have access to those types - at least to my knowledge.

aside from that, typegoose's hook types are a slight modification from mongoose's hook types, and from what i can tell, mongoose's types dont have anything specific set to `ModifyResult` or `findOneAndUpdate`

**Comment by FullStackSteve** [comment]
> there is currently no way to distinguish between `rawResult: true` and false inside a hooks types, because that is set on the operation level, and hooks dont have access to those types - at least to my knowledge.
> 
> aside from that, typegoose's hook types are a slight modification from mongoose's hook types, and from what i can tell, mongoose's types dont have anything specific set to `ModifyResult` or `findOneAndUpdate`

@hasezoey so should this issue be posted to https://github.com/Automattic/mongoose ?

**Comment by hasezoey** [comment]
> so should this issue be posted to https://github.com/Automattic/mongoose ?

as i am not aware of any special `rawResults` hook handling in terms of types on mongoose's side, yes

**Comment by FullStackSteve** [comment]
@hasezoey This has been posted as an issue [here](https://github.com/Automattic/mongoose/issues/13987) 

> > so should this issue be posted to https://github.com/Automattic/mongoose ?
> 
> as i am not aware of any special `rawResults` hook handling in terms of types on mongoose's side, yes

**Comment by hasezoey** [comment]
actually now that i look at the types more in-depth again, i have noticed:
- typegoose hook types are somewhat outdated (again) (though this should not change anything for this issue)
- mongoose hook types dont at all deal with the query result type because it is always set to `any` unless overwritten and there are no test showcasing usage of the overwrite

https://github.com/Automattic/mongoose/blob/236a7a76ede18cc99a95f9760faf241160814f5b/types/index.d.ts#L356-L358

so that means you either need to manually specify the generic, or some OR for all cases needs to be added so that the resulting type (parameter `doc` in your example) would be `QueryResultType<T> | ModifyResult<QueryResultType<T>>`

for now the type can be manually specified like:

```ts
@post<mongoose.Query<mongoose.ModifyResult<DocumentType<User>> | DocumentType<User>, DocumentType<User>>>(
  'findOneAndUpdate',
  function (doc, next) {
    doc; // Type: DocumentType<User, BeAnObject> | mongoose.ModifyResult<DocumentType<User, BeAnObject>>

    if ('save' in doc) {
      doc; // Type: DocumentType<User, BeAnObject>
    }
    if ('value' in doc && 'save' in (doc?.value || {})) {
      doc; // Type: mongoose.ModifyResult<DocumentType<User, BeAnObject>>
    }

    next();
  }
)
```

note that these checks will not work if the class itself has members named `value` and / or `save`

**Comment by FullStackSteve** [comment]
> ```ts
> mongoose.ModifyResult<DocumentType<User>> | DocumentType<User>, DocumentType<User>>
> ```

@hasezoey excellent thanks for the tip - refactored your proposal slightly and implemented as a working solution for others if they encounter same issue:

```ts
// Had issues compiling your proposal so refactored slightly
export type RawModifyResult<T> = mongoose.ModifyResult<DocumentType<T>> | DocumentType<T>;

@post<RawModifyResult<User>>('findOneAndUpdate', function (doc, next) {
  if ('save' in doc) {
    doc.id = doc._id;
    doc.save();
  }
  if ('value' in doc && doc.value && 'save' in doc.value) {
    doc.value.id = doc.value._id;
    doc.value.save();
  }
  next();
})
```
