### ISSUE TITLE
Trouble Inferring Complete Model Using 'Ref' in Typegoose for Type Completion

### ISSUE THREAD

**Issue by anandtpwebdura** [typegoose/typegoose#889]
I am working with two models in my application:

```typescript
class A {
  @prop({ ref: "B" })
  b: Ref<B>;
}

class B {
  @prop()
  _id: string;
  @prop()
  name: string;
  @prop()
  date: Date;
}

// I am attempting to use the following code:
const temp = objA.b.name;
```

However, in TypeScript, I am encountering an issue where it doesn't recognize the 'name' property, and it's showing that 'name' is not available.

I have tried a solution suggested in a related question:

```
import { RefType } from "@typegoose/typegoose/lib/types";
import mongoose from "mongoose";

// export declare type Ref<R, T extends RefType = mongoose.Types.ObjectId> = R | T;
export type Ref<R, T extends RefType = R extends { _id?: RefType } ? R["_id"] : mongoose.Types.ObjectId> = R | T;
```

The provided solution works for '_id' but does not extend the whole referenced model. I am looking for a way to properly infer the complete referenced model so that I can use it effectively.

## Versions

- System: macos / 
- NodeJS: 18.12.1
- Typescript: 5.0.2
- Compiler / Transpiler: tsc 
- Typegoose(NPM): 11.5.0
- mongoose: 7.0.3

---

**Comment by smolinari** [comment]
How are you getting `objA`?

Scott

**Comment by anandtpwebdura** [comment]
hi @smolinari 
Yeah, A is one of my Schema Model.
So let's say I have an endpoint to create a record with schema A. I did create it, but inside it I have a reference to B with property b.
So the way I can get objA is like : 

`const objA = ASchema.create(input);`

So when I get the variable objA, it should have the property b after populating from schema B right? I will using mongoose-autopopulate for that.

But when I'm writing the code for accessing objA.b.name typescript showing compilation error : `Property 'name' does not exist on type 'Ref<B>'.`

**Comment by smolinari** [comment]
So, again, how are you getting objA with population of b? At that point, you should have a type check for the document like shown here:  https://typegoose.github.io/typegoose/docs/api/functions/typeguards/is-document

Scott

**Comment by anandtpwebdura** [comment]
Mongoose-Autopopulate plugin will handle this automatically right? please correct me if I'm wrong.

**Comment by smolinari** [comment]
If you are querying for the A document, yes. It won't help you with just a `.create()`. How can it?

Scott

**Comment by hasezoey** [comment]
> It was given in the https://github.com/typegoose/typegoose/issues/144

that is a example from when typegoose did not have its own Ref type (or a way more basic form and i didnt fully understand it), but this will not work nowadays anymore

---

from what i can tell, your problem is that you dont narrow the type of your reference, if that is the case then there were plenty of similar issues in the past and there is a guide for that, namely [Reference other Classes](https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes) or more specifically for this case [Reference other Classes: Population](https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes#population) (also checkout the code-examples for [isDocument](https://typegoose.github.io/typegoose/docs/api/functions/typeguards/is-document) and its counterpart [isRefType](https://typegoose.github.io/typegoose/docs/api/functions/typeguards/is-ref-type)).

note that plugins cannot modify the type without you wrapping it in some custom type, also auto-population can fail the same way a normal `.populate` can fail (without error)

**Comment by anandtpwebdura** [comment]
@hasezoey 
Hey thanks for the message. Let me go through it and if it works for me I will close this issue

**Comment by anandtpwebdura** [comment]
@hasezoey @smolinari 
hey thanks for the messages. It worked. Closing this issue.
